apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstservice
  labels:
    app: firstservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: firstservice
  template:
    metadata:
      labels:
        app: firstservice
    spec:
      containers:
      - name: firstservice
        image: bhadrasayantan/firstservice:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /firstservice/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /firstservice/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
